version: '3.3'

services:
  nodejs:
     image: shyamachuthan/youcode
     volumes:
      - ./back-end:/usr/src/code
     ports:
       - "49160:3000"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress